# Generated by Django 5.2.6 on 2025-09-26 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=120)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('interes', models.CharField(blank=True, help_text='Área de interés, p. ej. Python, Web, Redes', max_length=80)),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True)),
                ('url', models.URLField(help_text='URL de YouTube/Vimeo u hospedaje propio')),
                ('categoria', models.CharField(blank=True, max_length=80)),
                ('publicado', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
